/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MainB */

#ifndef _Included_MainB
#define _Included_MainB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MainB
 * Method:    concat
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MainB_concat
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     MainB
 * Method:    strlen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_MainB_strlen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     MainB
 * Method:    strrev
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MainB_strrev
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
