/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MainA */

#ifndef _Included_MainA
#define _Included_MainA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MainA
 * Method:    Hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MainA_Hello
  (JNIEnv *, jclass);

/*
 * Class:     MainA
 * Method:    GetNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MainA_GetNum
  (JNIEnv *, jclass);

/*
 * Class:     MainA
 * Method:    Increment
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MainA_Increment
  (JNIEnv *, jclass, jint);

/*
 * Class:     MainA
 * Method:    Add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_MainA_Add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
