/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_print
  (JNIEnv *, jclass);

/*
 * Class:     Main
 * Method:    hello
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Main_hello
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
