/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ExceptionTypes */

#ifndef _Included_ExceptionTypes
#define _Included_ExceptionTypes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ExceptionTypes
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ExceptionTypes_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     ExceptionTypes
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_ExceptionTypes_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     ExceptionTypes
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ExceptionTypes_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ExceptionTypes
 * Method:    doIt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ExceptionTypes_doIt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
