/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    Hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_Hello
  (JNIEnv *, jclass);

/*
 * Class:     Main
 * Method:    GetNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Main_GetNum
  (JNIEnv *, jclass);

/*
 * Class:     Main
 * Method:    Increment
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Main_Increment
  (JNIEnv *, jclass, jint);

/*
 * Class:     Main
 * Method:    Add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Main_Add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
