/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PassingObject */

#ifndef _Included_PassingObject
#define _Included_PassingObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PassingObject
 * Method:    changeCountValue
 * Signature: (LSimpleClass;)V
 */
JNIEXPORT void JNICALL Java_PassingObject_changeCountValue
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
