/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    concat
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Main_concat
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     Main
 * Method:    strlen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Main_strlen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Main
 * Method:    strrev
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Main_strrev
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
